"""Initial Supabase Migration

Revision ID: 8cd4cd2afa64
Revises: 
Create Date: 2026-06-22 01:53:12.502565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd4cd2afa64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_roles',
    sa.Column('role_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('industry_category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_roles_role_name'), 'career_roles', ['role_name'], unique=True)
    op.create_table('learning_paths',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_duration', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', sa.Enum('beginner', 'intermediate', 'advanced', name='difficulty_level'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_learning_paths_difficulty_level'), 'learning_paths', ['difficulty_level'], unique=False)
    op.create_table('skills',
    sa.Column('skill_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('Programming', 'Database', 'Cloud', 'AI_ML', 'Data_Analytics', 'Frontend', 'Backend', 'DevOps', 'Soft_Skills', 'Other', name='skill_category'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=True)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('student', 'mentor', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('entity_name', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action_type'), 'activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('learning_path_skills',
    sa.Column('learning_path_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learning_path_id', 'skill_id', name='uq_learning_path_skills')
    )
    op.create_index(op.f('ix_learning_path_skills_learning_path_id'), 'learning_path_skills', ['learning_path_id'], unique=False)
    op.create_index(op.f('ix_learning_path_skills_skill_id'), 'learning_path_skills', ['skill_id'], unique=False)
    op.create_table('role_skills',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('importance_weight', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('importance_weight BETWEEN 1 AND 10', name='chk_role_skills_weight'),
    sa.ForeignKeyConstraint(['role_id'], ['career_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'skill_id', name='uq_role_skills')
    )
    op.create_index(op.f('ix_role_skills_role_id'), 'role_skills', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_skills_skill_id'), 'role_skills', ['skill_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('college_name', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=150), nullable=True),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('year_of_study', sa.SmallInteger(), nullable=True),
    sa.Column('graduation_year', sa.SmallInteger(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('target_role_id', sa.String(length=36), nullable=True),
    sa.Column('profile_completion_percentage', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('graduation_year BETWEEN 2000 AND 2040', name='chk_sp_graduation_year'),
    sa.CheckConstraint('profile_completion_percentage BETWEEN 0 AND 100', name='chk_sp_completion_pct'),
    sa.CheckConstraint('year_of_study BETWEEN 1 AND 6', name='chk_sp_year_of_study'),
    sa.ForeignKeyConstraint(['target_role_id'], ['career_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_target_role_id'), 'student_profiles', ['target_role_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('resumes',
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('upload_status', sa.Enum('uploaded', 'processing', 'analyzed', 'failed', name='upload_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_is_active'), 'resumes', ['is_active'], unique=False)
    op.create_index(op.f('ix_resumes_student_profile_id'), 'resumes', ['student_profile_id'], unique=False)
    op.create_index(op.f('ix_resumes_upload_status'), 'resumes', ['upload_status'], unique=False)
    op.create_table('student_dashboard_metrics',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('total_resumes_uploaded', sa.Integer(), nullable=False),
    sa.Column('latest_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('average_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('strongest_skill', sa.String(length=150), nullable=True),
    sa.Column('weakest_skill', sa.String(length=150), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_dashboard_metrics_student_id'), 'student_dashboard_metrics', ['student_id'], unique=True)
    op.create_table('analysis_results',
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('target_role_id', sa.String(length=36), nullable=False),
    sa.Column('readiness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skill_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('project_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('professional_presence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('recommendation_summary', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('professional_presence_score BETWEEN 0 AND 10', name='chk_ar_presence_score'),
    sa.CheckConstraint('project_score BETWEEN 0 AND 20', name='chk_ar_project_score'),
    sa.CheckConstraint('readiness_score BETWEEN 0 AND 100', name='chk_ar_readiness_score'),
    sa.CheckConstraint('skill_score BETWEEN 0 AND 70', name='chk_ar_skill_score'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['career_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_analyzed_at'), 'analysis_results', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_resume_id'), 'analysis_results', ['resume_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_target_role_id'), 'analysis_results', ['target_role_id'], unique=False)
    op.create_table('resume_parsed_data',
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('extracted_name', sa.String(length=255), nullable=True),
    sa.Column('extracted_email', sa.String(length=320), nullable=True),
    sa.Column('extracted_phone', sa.String(length=30), nullable=True),
    sa.Column('education_summary', sa.Text(), nullable=True),
    sa.Column('experience_summary', sa.Text(), nullable=True),
    sa.Column('projects_summary', sa.Text(), nullable=True),
    sa.Column('certifications_summary', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_parsed_data_resume_id'), 'resume_parsed_data', ['resume_id'], unique=True)
    op.create_table('resume_skills',
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('extraction_source', sa.Enum('rule_based', 'ai_extraction', 'manual', name='extraction_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name='chk_resume_skill_confidence'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'skill_id', name='uq_resume_skills')
    )
    op.create_index(op.f('ix_resume_skills_resume_id'), 'resume_skills', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_skills_skill_id'), 'resume_skills', ['skill_id'], unique=False)
    op.create_table('ai_recommendation_logs',
    sa.Column('analysis_result_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('token_usage >= 0', name='chk_arl_token_usage'),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendation_logs_analysis_result_id'), 'ai_recommendation_logs', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendation_logs_generated_at'), 'ai_recommendation_logs', ['generated_at'], unique=False)
    op.create_index(op.f('ix_ai_recommendation_logs_model_name'), 'ai_recommendation_logs', ['model_name'], unique=False)
    op.create_table('career_recommendations',
    sa.Column('analysis_result_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_role_id', sa.String(length=36), nullable=False),
    sa.Column('match_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rank_position', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('match_percentage BETWEEN 0 AND 100', name='chk_cr_match_pct'),
    sa.CheckConstraint('rank_position BETWEEN 1 AND 10', name='chk_cr_rank'),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_role_id'], ['career_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_result_id', 'recommended_role_id', name='uq_career_recommendations')
    )
    op.create_index(op.f('ix_career_recommendations_analysis_result_id'), 'career_recommendations', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_career_recommendations_recommended_role_id'), 'career_recommendations', ['recommended_role_id'], unique=False)
    op.create_table('mentor_feedback',
    sa.Column('analysis_result_id', sa.String(length=36), nullable=False),
    sa.Column('mentor_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('improvement_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='chk_mf_rating'),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_result_id', 'mentor_id', name='uq_mentor_feedback')
    )
    op.create_index(op.f('ix_mentor_feedback_analysis_result_id'), 'mentor_feedback', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_mentor_feedback_mentor_id'), 'mentor_feedback', ['mentor_id'], unique=False)
    op.create_table('skill_gap_analysis',
    sa.Column('analysis_result_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('gap_type', sa.Enum('matched', 'missing', 'recommended', name='gap_type'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_result_id', 'skill_id', name='uq_skill_gap_analysis')
    )
    op.create_index(op.f('ix_skill_gap_analysis_analysis_result_id'), 'skill_gap_analysis', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_skill_gap_analysis_gap_type'), 'skill_gap_analysis', ['gap_type'], unique=False)
    op.create_index(op.f('ix_skill_gap_analysis_skill_id'), 'skill_gap_analysis', ['skill_id'], unique=False)
    op.create_table('user_recommendations',
    sa.Column('analysis_result_id', sa.String(length=36), nullable=False),
    sa.Column('learning_path_id', sa.String(length=36), nullable=True),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('priority_level', sa.Enum('high', 'medium', 'low', name='priority_level'), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_recommendations_analysis_result_id'), 'user_recommendations', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_user_recommendations_learning_path_id'), 'user_recommendations', ['learning_path_id'], unique=False)
    op.create_index(op.f('ix_user_recommendations_priority_level'), 'user_recommendations', ['priority_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_recommendations_priority_level'), table_name='user_recommendations')
    op.drop_index(op.f('ix_user_recommendations_learning_path_id'), table_name='user_recommendations')
    op.drop_index(op.f('ix_user_recommendations_analysis_result_id'), table_name='user_recommendations')
    op.drop_table('user_recommendations')
    op.drop_index(op.f('ix_skill_gap_analysis_skill_id'), table_name='skill_gap_analysis')
    op.drop_index(op.f('ix_skill_gap_analysis_gap_type'), table_name='skill_gap_analysis')
    op.drop_index(op.f('ix_skill_gap_analysis_analysis_result_id'), table_name='skill_gap_analysis')
    op.drop_table('skill_gap_analysis')
    op.drop_index(op.f('ix_mentor_feedback_mentor_id'), table_name='mentor_feedback')
    op.drop_index(op.f('ix_mentor_feedback_analysis_result_id'), table_name='mentor_feedback')
    op.drop_table('mentor_feedback')
    op.drop_index(op.f('ix_career_recommendations_recommended_role_id'), table_name='career_recommendations')
    op.drop_index(op.f('ix_career_recommendations_analysis_result_id'), table_name='career_recommendations')
    op.drop_table('career_recommendations')
    op.drop_index(op.f('ix_ai_recommendation_logs_model_name'), table_name='ai_recommendation_logs')
    op.drop_index(op.f('ix_ai_recommendation_logs_generated_at'), table_name='ai_recommendation_logs')
    op.drop_index(op.f('ix_ai_recommendation_logs_analysis_result_id'), table_name='ai_recommendation_logs')
    op.drop_table('ai_recommendation_logs')
    op.drop_index(op.f('ix_resume_skills_skill_id'), table_name='resume_skills')
    op.drop_index(op.f('ix_resume_skills_resume_id'), table_name='resume_skills')
    op.drop_table('resume_skills')
    op.drop_index(op.f('ix_resume_parsed_data_resume_id'), table_name='resume_parsed_data')
    op.drop_table('resume_parsed_data')
    op.drop_index(op.f('ix_analysis_results_target_role_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_resume_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_analyzed_at'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_student_dashboard_metrics_student_id'), table_name='student_dashboard_metrics')
    op.drop_table('student_dashboard_metrics')
    op.drop_index(op.f('ix_resumes_upload_status'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_student_profile_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_is_active'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_target_role_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_role_skills_skill_id'), table_name='role_skills')
    op.drop_index(op.f('ix_role_skills_role_id'), table_name='role_skills')
    op.drop_table('role_skills')
    op.drop_index(op.f('ix_learning_path_skills_skill_id'), table_name='learning_path_skills')
    op.drop_index(op.f('ix_learning_path_skills_learning_path_id'), table_name='learning_path_skills')
    op.drop_table('learning_path_skills')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_learning_paths_difficulty_level'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_career_roles_role_name'), table_name='career_roles')
    op.drop_table('career_roles')
    # ### end Alembic commands ###
