"""add_ats_score_columns

Revision ID: 9fbacb723d45
Revises: a995dd4f5304
Create Date: 2026-07-30 05:11:59.104793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError

# revision identifiers, used by Alembic.
revision: str = '9fbacb723d45'
down_revision: Union[str, None] = 'a995dd4f5304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    columns_to_add = [
        ('required_skills_score', sa.Numeric(precision=5, scale=2), False, '0'),
        ('preferred_skills_score', sa.Numeric(precision=5, scale=2), False, '0'),
        ('responsibility_match_score', sa.Numeric(precision=5, scale=2), False, '0'),
        ('certification_score', sa.Numeric(precision=5, scale=2), False, '0'),
        ('semantic_score', sa.Numeric(precision=5, scale=2), False, '0'),
        ('final_ats_score', sa.Numeric(precision=5, scale=2), False, '0')
    ]
    for col_name, col_type, nullable, default in columns_to_add:
        try:
            op.add_column('analysis_results', sa.Column(col_name, col_type, nullable=nullable, server_default=default))
        except OperationalError:
            pass
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_column('analysis_results', 'final_ats_score')
    op.drop_column('analysis_results', 'semantic_score')
    op.drop_column('analysis_results', 'certification_score')
    op.drop_column('analysis_results', 'responsibility_match_score')
    op.drop_column('analysis_results', 'preferred_skills_score')
    op.drop_column('analysis_results', 'required_skills_score')
    # ### end Alembic commands ###
